# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Landing Pages do Marketing
email: marketing@resultadosdigitais.com.br
description: > # this means to ignore newlines until "baseurl:"
  Repositório dos modelos de Landing Pages do Marketing da Resultados Digitais.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://resultadosdigitais.com.br" # the base hostname & protocol for your site
twitter_username: resdigitais
sass:
    # style: compressed
    load_paths:
        - _sass
        - _components

# Build settings
markdown: kramdown
